layout_spectrum: 0.1727121
color:
  saturation: 0.4070923
  brandStrength: 0
  lightness: 0.8843181
  rhythmicContrast: 0.7985305
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.5417784
name: SWINKELS.BE
